# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee58da78b8f1b3891c02869670966ec1064f653cb90718176b4025a37b120a2abfc915ccfae373560f031d64acc5c047f17a3f714ce85f9d1ac7ff16bc2cbce8

test:
  secret_key_base: cb387392c54379453f4d0fc8b78b8fbce019e65a08f1437a7f1590ea79f4420746b862536baacbde666af2efbd826a9b8869bf6444552333eba460fc61bef300

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
